#!/bin/sh

../../sh/prot/prot gfile.c > gfile-prot.h

../../sh/prot/prot gf-conf.c >> gfile-prot.h
../../sh/prot/prot gf-crsr.c >> gfile-prot.h
../../sh/prot/prot gf-gconf.c >> gfile-prot.h
../../sh/prot/prot gf-outmap.c >> gfile-prot.h
../../sh/prot/prot gf-replay.c >> gfile-prot.h
../../sh/prot/prot gf-save.c >> gfile-prot.h
../../sh/prot/prot gf-town.c >> gfile-prot.h

cat gfile-prot.h
